apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.client.name }}
  labels:
    app: {{ .Values.client.name }}
    {{- include "murum.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.client.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-client:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
