{{- if .Values.server.envSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.envSecretName }}
  labels:
    {{- include "murum.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-password: {{ "changeme" | b64enc }}
{{- end }}
