apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.name }}
  labels:
    app: {{ .Values.server.name }}
    {{- include "murum.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            {{- range $key, $value := .Values.server.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.server.envSecretName }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.envSecretName }}
                  key: mongo-password
                  optional: true
            {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /apiapi
              port: {{ .Values.server.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.server.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
